config/routes.rb
Base64App::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers, :number_of_posts, :number_of_following, :number_of_followers
            post :show_microposts_for_user
        end
        
        collection do
            post :user_from_username
        end
    end
    
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    resources :microposts do
        member do
            post :create, :destroy, :repost
            get :thread_for_micropost, :like, :likes_for_micropost
        end
        collection do
          get :images_from_feed, :random_image
        end
    end
    
    resources :relationships, :only => [:create, :destroy]
    resources :mentions, :only => [:index, :new, :create, :destroy]
    resources :direct_messages, :only => [:index, :new, :create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/contact', :to => 'pages#contact'
    match '/news', :to => 'pages#news'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/mentions',    :to => 'pages#mentions'
    match '/home', :to => 'pages#home'
    match '/pages/mentions', :to => 'pages#mentions'
    root :to => 'pages#home'
    
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>	
	<span class="user">
		<% if current_user.show_username == true %>
			<% if feed_item.user.username %>
				<%= link_to feed_item.user.username, feed_item.user %>
			<% else %>
				<%= link_to feed_item.user.name, feed_item.user %>
			<% end %>
		<% else %>
			<%= link_to feed_item.user.name, feed_item.user %>
		<% end %>
	</span>
	<span class="content">
		<% if feed_item.image_url %>
			<%= auto_link(feed_item.content + " " + feed_item.image_url) %>
		<% else %>
			<%= auto_link(feed_item.content) %>
		<% end %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.<br />
	</span>
	<div class="btn-group">
		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="icon-cog"></i>
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<% if current_user?(feed_item.user) %>
				<a href=<%= "#" + unique_modal(feed_item.id, "Delete") %> data-toggle="modal">Delete</a>
			<% else %>
				<a href=<%= "#" + unique_modal(feed_item.id, "Reply") %> data-toggle="modal">Reply</a>
				<%= link_to "Like", like_micropost_path(feed_item.id) %>
			<% end %>
			<% if feed_item.in_reply_to %>
				<%= link_to "Show thread", micropost_path(feed_item.in_reply_to) %><br />
			<% end %>
			<% if feed_item.like_users.count > 0 %>
				<%= link_to "Show Likes", likes_for_micropost_micropost_path(feed_item) %>
			<% end %>
		</ul>
	</div>	

	<div class="modal fade" id=<%= unique_modal(feed_item.id, "Delete") %>>
		<div class="modal-header">
			<a class="close" data-dismiss="modal">&times;</a>
			<h3>Delete?</h3>
		</div>
		<div class="modal-body">
			<p>Delete this post?</p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Close</a>
			<%= link_to "Delete", feed_item, :class => "btn btn-danger", :method =>  :delete, :title =>   feed_item.content %>
		</div>
	</div>

	<div class="modal fade" id=<%= unique_modal(feed_item.id, "Reply") %>>
		<div class="modal-header">
			<a class="close" data-dismiss="modal">&times;</a>
			<h3>Reply</h3>
		</div>
		<div class="modal-body">
			<%= form_for(@micropost) do |f| %>
			<div class="field">
				<%= f.text_area :content, :value => "@" + feed_item.user.username, :cols => "10", :rows => "8" %>
				<%= f.hidden_field :in_reply_to, :value => feed_item.id  %>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<%= f.submit "Reply", :class => "btn btn-primary" %>
			</div>
			<% end %>
		</div>
	</div>
</li>

app/views/shared/_like_user.html.erb
<li id="<%= like_user.id %>">
    
	<%= link_to gravatar_for(like_user) %>

	<span class="user">
		<%= like_user.name %>
	</span>
	<span class="content">
		<%= like_user.username %>
	</span>
</li>

app/views/shared/_mentions.html.erb
<% if @mentions.any? %>
<ol class="microposts">
	<%= render :partial => 'shared/mentions_item', :collection => @mentions %>
</ol>
<%= will_paginate @mentions %>
<% end %>

app/views/shared/_mentions_item.html.erb
<li id="<%= mentions_item.id %>">

	<% @another_temp = find_user_from_mention(mentions_item.sender_user_id) %>

	<%= link_to gravatar_for(@another_temp), @another_temp %>	

	<span class="user">
		<% if current_user.show_username == true %>
			<% if @another_temp.username %>
				<%= link_to @another_temp.username, @another_temp %>
			<% else %>
				<%= link_to @another_temp.name, @another_temp %>
			<% end %>
		<% else %>
			<%= link_to @another_temp.name, @another_temp %>
		<% end %>
	</span>
	<span class="content"><%= auto_link(mentions_item.content) %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(mentions_item.created_at) %> ago.
	</span>	
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.text_area :content, :placeholder => "Compose new micropost..." %>
	<div>Characters remaining: <span id="counter">256</span> <%= f.file_field :image, :accept => "image/x-png, image/gif, image/jpeg" %> </div>
</div>
<%= f.submit "Post", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_reply_item.html.erb
<li id="<%= reply_item.id %>">
    <%= link_to gravatar_for(reply_item.user), reply_item.user %>
    <span class="user">
        <% if current_user.show_username == true %>
            <% if reply_item.user.username %>
                <%= link_to reply_item.user.username, reply_item.user %>
            <% else %>
                <%= link_to reply_item.user.name, reply_item.user %>
            <% end %>
        <% else %>
            <%= link_to reply_item.user.name, reply_item.user %>
        <% end %>
    </span>
    <span class="content">
        <% if reply_item.image_url %>
            <%= auto_link(reply_item.content + " " + reply_item.image_url) %>
        <% else %>
            <%= auto_link(reply_item.content) %>
        <% end %>
    </span>
    <span class="timestamp">Posted <%= time_ago_in_words(reply_item.created_at) %> ago.
        <% if reply_item.in_reply_to %>
            In reply to <%= link_to "this post.", micropost_path(reply_item.in_reply_to) %>
        <% end %>
    </span>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, :size => 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<h4>
	<%= current_user.username %>
</h4>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>