config/routes.rb
Base64App::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers, :number_of_posts, :number_of_following, :number_of_followers
            post :show_microposts_for_user
        end
        
        collection do
            post :user_from_username
        end
    end
    
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    resources :microposts do
        member do
            post :create, :destroy, :repost
            get :thread_for_micropost, :like, :likes_for_micropost
        end
        collection do
          get :images_from_feed, :random_image
        end
    end
    
    resources :relationships, :only => [:create, :destroy]
    resources :mentions, :only => [:index, :new, :create, :destroy]
    resources :direct_messages, :only => [:index, :new, :create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/contact', :to => 'pages#contact'
    match '/news', :to => 'pages#news'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/mentions',    :to => 'pages#mentions'
    match '/home', :to => 'pages#home'
    match '/pages/mentions', :to => 'pages#mentions'
    root :to => 'pages#home'
    
end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
	<a href="http://www.jukaela.com/">Jukaela Enterprises</a>
	makes software that doesn't suck.  Look us up!
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	Contact Jukaela support at <a href="mailto:support@jukaela.com">support@jukaela.com</a>.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	Get help on Ruby on Rails Tutorial at the
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<meta name="apple-itunes-app" content="app-id=562749090"> 
<% if signed_in? %>
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="span8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>
<% else %>
<div class="center hero-unit">
	<h1>Welcome to Jukaela Social</h1>
	<br />
	<div class="row">
		<div class="span5">
			<h2><em>The Question</em></h2>
			<p>People come to us <em>all the time</em> saying, "I'm so sick of FaceSpace and Chipper.  What should I do?"  There are many things that I could tell you to do.  You could get a new dog.  You could learn to play an instrument, or you could continue reading this banter!</p><%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %>
		</div>
		<div class="span5">
			<ul class="thumbnails">
				<li class="span5">
					<a href="#" class="thumbnail">
						<img src="assets/sadFace.jpg" alt="">
						<h5>Sad Person Is Sad</h5>
						<p>This person is sad because you don't use Jukaela Social</p>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<blockquote><p>This is probably the greatest website in the history of the world.  People in ancient times called, they said that they wish they had this social platform.</p><small>Ima Person, April 30th, 2012</small></blockquote>

	<div class="row">
		<div class="span5">
			<ul class="thumbnails">
				<li class="span5">
					<a href="#" class="thumbnail">
						<img src="assets/happyPerson.jpg" alt="">
						<h5>Wow!</h5>
						<p>This man might have started using Jukaela Social recently!</p>
					</a>
				</li>
			</ul>
		</div>
		<div class="span5">
			<h2><em>The Answer</em></h2>
			<p>The answer is clear, my friends!  Sign up for a new social network.  Jukaela Social is nothing like the others!  Jukaela Social doesn't have fancy nonsense like <em>features</em>.  Jukaela Social is still in it's infancy.  It will probably lose all of your data, and it might even kick your dog!</p><%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %>
		</div>
	</div>

	<h2><em>Sign up now!</em></h2>
	<p>Sign up for Jukaela Social today!  It's probably worth your effort, and it might not cause you to catch tuberculosis!</p>
	<%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %><br />

</div>

<% end %>

app/views/pages/mentions.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for current_user %>
				<%= current_user.name %>
			</h1>
			<h4>
				<% if current_user.username %>
				<%= current_user.username %>
				<% else %>
				<script type="text/javascript">
					$(window).load(function(){
						$('#no_user_name').modal('show');
					});
				</script>
				<% end %>
			</h4>
		</section>
		<section>
			<% if current_user.profile %>
			<%= auto_link(current_user.profile) %>
			<% else %>
			<div>User hasn't defined a profile.</div>
			<% end %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="span8">
		<% if current_user.mentions.any? %>
		<h3>Mentions (<%= current_user.mentions.count %>)</h3>
		<ol class="microposts">
			<%= render 'shared/mentions' %>
		</ol>
		<%= will_paginate @mentions %>
		<% end %>
	</div>
</div>
</div>

<div class="modal fade" id="no_user_name" %>
<div class="modal-header">
	<a class="close" data-dismiss="modal">&times;</a>
	<h3>Specify User Name</h3>
</div>
<div class="modal-body">
	<p>Jukaela Social now has usernames!  Holy cow!  You will now be redirected to your Profile page to specify one.</p>
</div>
<div class="modal-footer">
	<%= link_to "Update", edit_user_path(current_user), :class => "btn btn-primary" %>
</div>

app/views/pages/news.html.erb
<h1>News</h1>
<div class="span11">
	<div class="row">
		<dt>May 15th, 2012</dt>
		<dd>Add email address of posting user to micropost json.  This speeds up the iOS front end tremendously.</dd>
	</div>
	<div class="row">
		<dt>May 13th, 2012</dt>
		<dd>Add username to microposts model</dd>
		<dd>Refactor code reuse in microposts controller</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 12th, 2012</dt>
		<dd>Demand that device tokens be unique.  This fixes the bug where you would receive multiple push notifications for each mention.</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 11th, 2012</dt>
		<dd>Further work for push notifications</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 9th, 2012</dt>
		<dd>Add APNS field to users table</dd>
		<dd>Implement push notifications</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 8th, 2012</dt>
		<dd>Began json work for relationships_controller</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 7th, 2012</dt>
		<dd>Add name to micropost model.  This allows a much more streamlined home.json</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 4th, 2012</dt>
		<dd>Fix authentication for json</dd>
		<dd>Implement posting from json</dd>
	</div>	
	<br />
	<div class="row">
		<dt>May 3rd, 2012</dt>
		<dd>Begin JSON implemention</dd>
		<dd>Allow feed to be downloaded via JSON.</dd>
		<dd>Split rendering of all controllers into html and json</dd>
		<dd>Fix crasher that would happen if a user that didn't exist was mentioned</dd>
		<dd>The wrong person was being sent the email when they began following somone.  Fixed.</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 1st, 2012</dt>
		<dd>Implement preference to show username in feed</dd>
		<dd>Implement @ replies.  Uses username.  If you wish to use a person's real name, use quotes</dd>
		<dd>Update of styling of news page</dd>
		<dd>Page for showing mentions</dd>
		<dd>Fix bug that was showing the wrong users on the mentions page</dd>
		<dd>Fix bug that would show username warning to wrong user</dd>
		<dd>Redirect to home page after sign in</dd>
	</div>
	<br />
	<div class="row">
		<dt>May 1st, 2012</dt>
		<dd>Happy May Day!</dd>
		<dd>Change email fields to use proper HTML 5 types so that the email keyboard is used on iOS.</dd>
		<dd>Fix branding and a typo in the emails</dd>
		<dd>Add glyph icons to _header</dd>
		<dd>Add ability to repost or reply to a post</dd>
		<dd>If the post contains a link, make the link clickable</dd>
		<dd>User now has the ability to set a profile.  Max 300 chars.</dd>
		<dd>If profile has link, make it clickable</dd>
		<dd>Change action menu style on feed</dd>
		<dd>Implement usernames</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 30th, 2012</dt>
		<dd>Major redesign</dd>
		<dd>Fix pagination in new style</dd>
		<dd>Major redesign of homepage</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 29th, 2012</dt>
		<dd>Change email fields to use proper HTML 5 types so that the email keyboard is used on iOS.</dd>
		<dd>Add counter for number of characters in micropost.</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 28th, 2012</dt>
		<dd>Support for admin users.</dd>
		<dd>Add support for deleting one's own posts.</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 27th, 2012</dt>
		<dd>Update logo.</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 26th, 2012</dt>
		<dd>Made the home page more functional and nicer looking</dd>
		<dd>Added session management.  This replaces the older style cookie support.</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 25th, 2012</dt>
		<dd>Made the News page look a little nicer.</dd>
		<dd>Added News page.</dd>
		<dd>Fixed a bug that caused the app to crash if you used quotes in a micropost.</dd>
		<dd>Added support for email notifications.</dd>
	</div>
	<br />
	<div class="row">
		<dt>April 24th, 2012</dt>
		<dd>Initial deployment!</dd>
	</div>
	<br />
</div>