config/routes.rb
Base64App::Application.routes.draw do
    resources :users do
        member do
            get :following, :followers, :number_of_posts, :number_of_following, :number_of_followers
            post :show_microposts_for_user
        end
        
        collection do
            post :user_from_username
        end
    end
    
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    resources :microposts do
        member do
            post :create, :destroy, :repost
            get :thread_for_micropost, :like, :likes_for_micropost
        end
        collection do
          get :images_from_feed, :random_image
        end
    end
    
    resources :relationships, :only => [:create, :destroy]
    resources :mentions, :only => [:index, :new, :create, :destroy]
    resources :direct_messages, :only => [:index, :new, :create, :destroy]

    match '/signup', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/contact', :to => 'pages#contact'
    match '/news', :to => 'pages#news'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/mentions',    :to => 'pages#mentions'
    match '/home', :to => 'pages#home'
    match '/pages/mentions', :to => 'pages#mentions'
    root :to => 'pages#home'
    
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", news_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Jukeala Social", root_path, :id => "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to content_tag(:i, "", :class => "icon-home icon-white") + " Home", root_path %></li>
					<% if signed_in? %>
					<li><%= link_to content_tag(:i, "", :class => "icon-star icon-white") + " Users", users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to content_tag(:i, "", :class => "icon-user") + " Profile", current_user %></li>
							<li><%= link_to content_tag(:i, "", :class => "icon-cog") + " Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to content_tag(:i, "", :class => "icon-lock") + " Sign out", signout_path, :method => "delete" %></li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to content_tag(:i, "", :class => "icon-lock icon-white") + " Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag "application" %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<section class="round">				
			<% flash.each do |key, value| %>
			<div class="alert alert-info <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>